name: amn  # you can edit this if you want

channels:
  - defaults
dependencies:
  # If any of your packages pulls in cudatoolkit:
  # uncomment the line below to make sure it matches
  # the output of `!echo $CUDA_VERSION` on colab
  # and take only the major.minor components
  # Right now, Colab uses CUDA 11.1
  # - cudatoolkit =11.1

  # Add your dependencies below this line
  # -------------------------------------
  - h5py=3.2.1
  - numpy=1.20.3
  - numpy-base=1.20.3
  - pandas=1.3.3
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - keras=2.6.0
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - sympy=1.8
  - pydoe2=1.3.0
  - cobra=0.22.1
  - pip:
    - silence-tensorflow==1.1.1