name: amn

channels:
  - defaults
dependencies:
  # Add your dependencies below this line
  # -------------------------------------
  - pydoe2=1.3.0
  - cobra=0.22.1
  - pip:
    - silence-tensorflow==1.1.1
